### ISSUE TITLE
Add NAND NOR XOR table in mathematical reasoning section with their info

### ISSUE THREAD

**Issue by gnikita432** [makesmatheasy/makesmatheasy#1330]
## **Is your feature request related to a problem? Please describe.**

- Add NAND NOR XOR table in mathematical reasoning section with their info

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by Furquan712** [comment]
I would like to work on this, will you assign me?

**Comment by Amit366** [comment]
@sairish2001 can I work??
