### ISSUE TITLE
Right regular heptagonal prism calculator

### ISSUE THREAD

**Issue by mehabhalodiya** [makesmatheasy/makesmatheasy#1508]
I would like to add `Right regular heptagonal prism` calculator under 3D shapes section.
Please assign this to me.

**Comment by Ankita297** [comment]
@sairish2001 Can i work on this ?

**Comment by mehabhalodiya** [comment]
@Ankita297 I will submit a PR for this within two days. It got delayed as I have my vivas and submissions going on.

Kindly requesting you to find other issues.
