### ISSUE TITLE
Update the contact section

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [makesmatheasy/makesmatheasy#1579]
I want to :

- [ ] Add validation to the last  input field of form
- [ ] Make the text at bottom of google form aligned properly in smaller views.

[GSSOC'21]

Screenshot:
![googleform](https://user-images.githubusercontent.com/66208607/116789319-ec089300-aacb-11eb-944e-5d73a7f9a5eb.png)

Please assign me this issue @sairish2001

**Comment by Bhavya-Sehgal** [comment]
@sairish2001 Please assign me this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 May,2021

**Comment by Ankita297** [comment]
@sairish2001 @shrey27tri01 can i work on this ?

**Comment by Ankita297** [comment]
@sairish2001 @shrey27tri01 Can i work on this ?

**Comment by shrey27tri01** [comment]
@Ankita297 Sure! Go ahead.
Deadline 25 May 2021 11:59 PM IST

**Comment by Ankita297** [comment]
@shrey27tri01 @sairish2001 for this issue i have to create new  google form then i will transfer the owner ship right ?
![screencapture-file-F-makesmatheasy-github-io-contact-html-2021-05-24-22_05_10](https://user-images.githubusercontent.com/67833077/119380224-0fdf8300-bcde-11eb-8675-ae70d0bbf86d.png)
![screencapture-file-F-makesmatheasy-github-io-contact-html-2021-05-24-22_19_36](https://user-images.githubusercontent.com/67833077/119380310-2dace800-bcde-11eb-9dc8-a24ee691b753.png)

**Comment by sairish2001** [comment]
> @shrey27tri01 @sairish2001 for this issue i have to create new  google form then i will transfer the owner ship right ?
> ![screencapture-file-F-makesmatheasy-github-io-contact-html-2021-05-24-22_05_10](https://user-images.githubusercontent.com/67833077/119380224-0fdf8300-bcde-11eb-8675-ae70d0bbf86d.png)
> ![screencapture-file-F-makesmatheasy-github-io-contact-html-2021-05-24-22_19_36](https://user-images.githubusercontent.com/67833077/119380310-2dace800-bcde-11eb-9dc8-a24ee691b753.png)
> 

No need to create a new form, I will put validation by myself

**Comment by Ankita297** [comment]
@sairish2001 Sir you can close this issue as the only probelm is with validation and text is at center already
