### ISSUE TITLE
Add working steps for Error detection a message in Hamming Code( for odd)

### ISSUE THREAD

**Issue by AB-san** [makesmatheasy/makesmatheasy#1656]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by AB-san** [comment]
i wouldlike to work on this isue

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 May,2021
