### ISSUE TITLE
Add working steps for decimal / bcd code converter

### ISSUE THREAD

**Issue by AB-san** [makesmatheasy/makesmatheasy#1658]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by AB-san** [comment]
i would like to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 May,2021

**Comment by Amit366** [comment]
@sairish2001 can I work??

**Comment by AB-san** [comment]
@Amit366 I have already completed this , just about to push!!

**Comment by sairish2001** [comment]
Go ahead
Deadline 31 May,2021
