### ISSUE TITLE
To add steps of calculation for eigen values of a matrix

### ISSUE THREAD

**Issue by abhijeet141** [makesmatheasy/makesmatheasy#1661]
## **Is your feature request related to a problem? Please describe.**

To add steps of calculation for eigen values of a matrix

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 May,2021
