### ISSUE TITLE
To add a calculator to calculate shortest distance between two vector Lines

### ISSUE THREAD

**Issue by abhijeet141** [makesmatheasy/makesmatheasy#1856]
## **Is your feature request related to a problem? Please describe.**

To add a calculator to calculate shortest distance between two vector Lines

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by Nidhirajput1301** [comment]
Go ahead
Deadline 14 May,2021
