### ISSUE TITLE
add hexadecimal/gray code converter

### ISSUE THREAD

**Issue by AB-san** [makesmatheasy/makesmatheasy#1907]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

i would like to add this converter

**Comment by Nidhirajput1301** [comment]
Go ahead
Deadline 14 May,2021

**Comment by AB-san** [comment]
i already added this feature in different issue
