### ISSUE TITLE
add working steps for hex/gray code converter

### ISSUE THREAD

**Issue by AB-san** [makesmatheasy/makesmatheasy#1908]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

i wud lk 2 wrk on dis isu

**Comment by Nidhirajput1301** [comment]
Go ahead
Deadline 14 May,2021

**Comment by Amit366** [comment]
@sairish2001 can i work since the deadline is passed??

**Comment by AB-san** [comment]
closing this issue as it already exists
