### ISSUE TITLE
add working steps for octal/gray code converter

### ISSUE THREAD

**Issue by AB-san** [makesmatheasy/makesmatheasy#1911]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

i owudl like to work on this issue

**Comment by Nidhirajput1301** [comment]
Go ahead
Deadline 14 May,2021

**Comment by AB-san** [comment]
issue already exists
