### ISSUE TITLE
To add Working Steps in Skewness Calculator

### ISSUE THREAD

**Issue by abhijeet141** [makesmatheasy/makesmatheasy#2053]
## **Is your feature request related to a problem? Please describe.**

To add Working Steps in Skewness Calculator

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 16 May,2021

**Comment by shonali2600** [comment]
@sairish2001 can I work on this as the deadline is over?

**Comment by sairish2001** [comment]
Go ahead
Deadline 31 May,2021
