### ISSUE TITLE
Add calculator for calculating factor pairs for negative input also

### ISSUE THREAD

**Issue by AB-san** [makesmatheasy/makesmatheasy#2126]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/71064674/117630026-6609dd80-b198-11eb-8b3b-55482b0d5eb8.png)

current factorization calculator finds pairs for positive numbers only

**Comment by AB-san** [comment]
i wud like to work on this

**Comment by sairish2001** [comment]
Go ahead
Deadline 17 May,2021
