### ISSUE TITLE
modify log calculator to calculate log values when base is 0<x<1

### ISSUE THREAD

**Issue by AB-san** [makesmatheasy/makesmatheasy#2145]
## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![image](https://user-images.githubusercontent.com/71064674/117638776-d3ba0780-b1a0-11eb-9bdd-96894ae71027.png)

i wud like to work on this

**Comment by sairish2001** [comment]
Go ahead
Deadline 20 May,2021
