### ISSUE TITLE
add working stpes for bcd to hex converter 

### ISSUE THREAD

**Issue by AB-san** [makesmatheasy/makesmatheasy#2187]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

i wud like ot work on thsi

**Comment by sairish2001** [comment]
Go ahead
Deadline 20 May,2021

**Comment by AB-san** [comment]
issues already exists
