### ISSUE TITLE
add working steps for octal to bcd convertr

### ISSUE THREAD

**Issue by AB-san** [makesmatheasy/makesmatheasy#2190]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

i wud like to add this

**Comment by sairish2001** [comment]
Go ahead
Deadline 20 May,2021

**Comment by Amit366** [comment]
@sairish2001 can I work??

**Comment by sairish2001** [comment]
Go ahead Deadline 31 May,2021
