### ISSUE TITLE
Probability calculator

### ISSUE THREAD

**Issue by Upasana1216** [makesmatheasy/makesmatheasy#220]
Given a problem it will calculate the probability and will also provide the stepwise solution to the user.

Please assign this to me

**Comment by sairish2001** [comment]
Feel free to ask your doubts, if any
Deadline 22 March,2021 (11:59 PM IST)

**Comment by Upasana1216** [comment]
Okay sir

**Comment by Upasana1216** [comment]
Sir, I have designed a probability calculator but it can calculate the probability of drawing a card given the number of copies in your deck, the number of cards in your deck, and the number of cards you are drawing.

**Comment by sairish2001** [comment]
Can you show steps for the same?

**Comment by Upasana1216** [comment]
No sir.

**Comment by Khushi-agarwal** [comment]
@sairish2001 @arpit456jain kindly assign me this issue under lgm-soc.

**Comment by arpit456jain** [comment]
@Khushi-agarwal go ahead 
Dead line 27 june
