### ISSUE TITLE
To add a calculator for calculating Distance between Incenter and Circumcenter of a triangle

### ISSUE THREAD

**Issue by abhijeet141** [makesmatheasy/makesmatheasy#2211]
## **Is your feature request related to a problem? Please describe.**

To add a calculator for calculating Distance between Incenter and Circumcenter of a triangle

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 May,2021

**Comment by satyampgt4** [comment]
is this issue still open 
### _**As deadline is over**_ 
can i work on it

**Comment by abhijeet141** [comment]
@satyampgt4 I will complete this issue positively by today if I am not able to do I will unassigned myself :)
