### ISSUE TITLE
Improve the UI of Mean calculator

### ISSUE THREAD

**Issue by gnikita432** [makesmatheasy/makesmatheasy#2240]
## Proposal

(A clear and concise description of what the proposal is.)

https://user-images.githubusercontent.com/61223163/117786382-0f1d0a80-b263-11eb-9ed1-6c61b9db5c87.mp4

Their is a lot of gap between items they could be aligned in a row.

I would like to work on this issue

**Comment by abhijeet141** [comment]
@gnikita432  This issue is already present #2144  please close this issue
