### ISSUE TITLE
Antilog calculator

### ISSUE THREAD

**Issue by shonali2600** [makesmatheasy/makesmatheasy#2252]
I would like to add antilog calculator.

**Comment by Amit366** [comment]
@sairish2001 can I work??

**Comment by sairish2001** [comment]
Go ahead

**Comment by shonali2600** [comment]
@sairish2001 I created this issue, and specified as well that I want to work on this, so it should be assigned to me na?

**Comment by sairish2001** [comment]
Sorry my bad, @shonali2600 you can start working on it
