### ISSUE TITLE
Adding steps for coprime checker

### ISSUE THREAD

**Issue by madihamallick** [makesmatheasy/makesmatheasy#2283]
**I would like to add steps for  coprime checker calculator. Please assign this to me.** 

![5](https://user-images.githubusercontent.com/70858557/117827166-62f11900-b28e-11eb-8b69-c97b0bdf95ca.PNG)

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 May,2021

**Comment by Amit366** [comment]
@sairish2001 can I add the steps since the deadline has passed?

**Comment by madihamallick** [comment]
@Amit366 I'm working on this...will make a PR soon

**Comment by sairish2001** [comment]
Go ahead
