### ISSUE TITLE
To add working steps in sum of n terms of AP if number of terms and AP is given

### ISSUE THREAD

**Issue by abhijeet141** [makesmatheasy/makesmatheasy#2354]
## **Is your feature request related to a problem? Please describe.**

To add working steps in sum of n terms of AP if number of terms and AP is given

**Comment by abhijeet141** [comment]
**Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018**

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 May,2021

**Comment by shonali2600** [comment]
@sairish2001 can i work on this as deadline is over?

**Comment by sairish2001** [comment]
Go ahead
Deadline 31 May,2021
