### ISSUE TITLE
to add calculator for calculating circumradius of a cyclic quadrilateral

### ISSUE THREAD

**Issue by abhijeet141** [makesmatheasy/makesmatheasy#2369]
## **Is your feature request related to a problem? Please describe.**

to add calculator for calculating circumradius of a cyclic quadrilateral

**Comment by abhijeet141** [comment]
**Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018**

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 May,2021
