### ISSUE TITLE
To add a calculator to calculate area and circum radius of excentral triangle

### ISSUE THREAD

**Issue by abhijeet141** [makesmatheasy/makesmatheasy#2370]
## **Is your feature request related to a problem? Please describe.**

To add a calculator to calculate area and circum radius of excentral triangle

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 May,2021

**Comment by Amit366** [comment]
@sairish2001 can i work??

**Comment by abhijeet141** [comment]
@Amit366 i am still working on this

**Comment by Amit366** [comment]
@abhijeet141 but the deadline is over

**Comment by abhijeet141** [comment]
@Amit366 don't worry i will complete all my assigned issue by tomorrow

**Comment by Amit366** [comment]
@abhijeet141 but its not fair. How can one still work after the deadline @sairish2001

**Comment by sairish2001** [comment]
@Amit366 
Go ahead
Deadline 31 May,2021
