### ISSUE TITLE
Add calculator tht takes 3 inputs and checks if they r pythogorean triplet under pythogorean triplet section

### ISSUE THREAD

**Issue by AB-san** [makesmatheasy/makesmatheasy#2377]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

i wud like ot work on htis

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 May,2021

**Comment by satyampgt4** [comment]
is this issue still open 
as deadline is over can i work on it

**Comment by AB-san** [comment]
> is this issue still open
> as deadline is over can i work on it

i am still working on it
