### ISSUE TITLE
Add working step for pythogorean triplet checker

### ISSUE THREAD

**Issue by AB-san** [makesmatheasy/makesmatheasy#2378]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

i wud like to work on this

**Comment by madihamallick** [comment]
@AB-san this issue exists, #1755

**Comment by AB-san** [comment]
@madihamallick  actually this is a different issue 
in this issue i will add steps to calculator that will check  if three inputs given are pythogorean triplets or not!!

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 May,2021
