### ISSUE TITLE
To add a calculator to calculate distance between incentre and excentre

### ISSUE THREAD

**Issue by abhijeet141** [makesmatheasy/makesmatheasy#2384]
## **Is your feature request related to a problem? Please describe.**

To add a calculator to calculate distance between incentre and excentre

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 May,2021

**Comment by Amit366** [comment]
@sairish2001 can i work??

**Comment by abhijeet141** [comment]
@sairish2001 I think till now i am assigned for this issue

**Comment by Amit366** [comment]
@sairish2001 since the deadline is passed and also only a fews days are left so I made the PR. And  also in discord a mentor has said that we can make PRs even if they aren't assigned as only 5 days are left.
