### ISSUE TITLE
To add a calculator for calculating equation of a plane in intercept form

### ISSUE THREAD

**Issue by abhijeet141** [makesmatheasy/makesmatheasy#2388]
## **Is your feature request related to a problem? Please describe.**

To add a calculator for calculating equation of a plane in intercept form

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 May,2021

**Comment by Amit366** [comment]
@sairish2001 can I work??

**Comment by sairish2001** [comment]
@Amit366 go ahead
Deadline 31 May,2021
