### ISSUE TITLE
Add calculator for Effective Interest Rate for m period

### ISSUE THREAD

**Issue by AB-san** [makesmatheasy/makesmatheasy#2410]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

the current calculator calculates only for  Effective Interest Rate  per period
i would like to add  Effective Interest Rate for m period

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 May,2021
