### ISSUE TITLE
Add calculator to find percent rate per compounding period 'm' under effective intrest rate section

### ISSUE THREAD

**Issue by AB-san** [makesmatheasy/makesmatheasy#2412]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

i wud like to add it

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 May,2021

**Comment by Amit366** [comment]
@sairish2001 can I work?

**Comment by AB-san** [comment]
> @sairish2001 can I work?

actually i have already solved this pr , i am just about to send the pr
