### ISSUE TITLE
To add working steps in Insert n-AM between two numbers

### ISSUE THREAD

**Issue by abhijeet141** [makesmatheasy/makesmatheasy#2457]
## **Is your feature request related to a problem? Please describe.**

To add working steps in Insert n-AM between two numbers

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 May,2021

**Comment by Amit366** [comment]
@sairish2001 can I work on this issue as the deadline is over??

**Comment by abhijeet141** [comment]
@Amit366 In this issue i will be adding steps in the calculator section so whatever input will be given you will get all steps if you are thinking to do same changes then @sairish2001 you can assign him

**Comment by sairish2001** [comment]
Go ahead
Deadline 31 May,2021
