### ISSUE TITLE
add working steps for distnc betn 2 planes under 3d geomtry

### ISSUE THREAD

**Issue by AB-san** [makesmatheasy/makesmatheasy#2511]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.
i wd lk 2 wrk on dis

**Comment by sairish2001** [comment]
Go ahead
Deadline 24 May,2021
