### ISSUE TITLE
Valid error message in Ztest  t-test and chi square test

### ISSUE THREAD

**Issue by abhijeet141** [makesmatheasy/makesmatheasy#2536]
## **Describe the bug**

Valid error message in Ztest  t-test and chi square test

## **Screenshots**
![image](https://user-images.githubusercontent.com/67696867/118350895-94abfd80-b576-11eb-8a46-36167fc1a4a7.png)

**Comment by abhijeet141** [comment]
Hi, I want to work on this issue I will start working on it as soon as I get assigned!! I am a part of GSSoC'21.
Kindly assign this issue to me!
Discord Username : Abhijeet Sinha(P)
Discord Tag: #4018

**Comment by sairish2001** [comment]
Go ahead
Deadline 24 May,2021
