### ISSUE TITLE
Cylindrical to cartesian coordinate calculator

### ISSUE THREAD

**Issue by khareyash05** [makesmatheasy/makesmatheasy#2694]
I would like to add calculator to convert cylindrical coordinates to cartesian cooriantes

**Comment by Amit366** [comment]
@sairish2001 I have done this issue.

**Comment by khareyash05** [comment]
@Amit366 can u pls referr the PR?

**Comment by Amit366** [comment]
@khareyash05 what happened??

**Comment by khareyash05** [comment]
Can you pls share the PR no. @Amit366
