### ISSUE TITLE
Polar to Cylindrical Coordinates convertor

### ISSUE THREAD

**Issue by khareyash05** [makesmatheasy/makesmatheasy#2697]
I would like to convert polar coordinates to cylindrical coordinates

**Comment by shonali2600** [comment]
@khareyash05 can I work on this? as you have already a lot of issues to work on and time is very little.

**Comment by khareyash05** [comment]
Go ahead. @shonali2600

**Comment by shonali2600** [comment]
@khareyash05 thanks :)
