### ISSUE TITLE
create a signin signup page.

### ISSUE THREAD

**Issue by gnikita432** [makesmatheasy/makesmatheasy#2727]
## Proposal

(A clear and concise description of what the proposal is.)
I would like to create a sign-in sign-up page for makesmatheasy.

**Comment by gnikita432** [comment]
@sairish2001 should I work on this issue?

**Comment by bansiparsania** [comment]
Please assign this to me ..bcz I'll create sign in sign up page

**Comment by sairish2001** [comment]
@bansiparsania We don't have such plans till now, So I am closing this issue
