### ISSUE TITLE
Pentatope calculator

### ISSUE THREAD

**Issue by khareyash05** [makesmatheasy/makesmatheasy#2772]

**Comment by Amit366** [comment]
@sairish2001 can i work?

**Comment by khareyash05** [comment]
@Amit366 that's not in the spirit of open source that i had made the issue for myself and you made a PR for the same

@sairish2001 please tell me if I am wrong

**Comment by Amit366** [comment]
@khareyash05 it's been more than 14 days since u created the issue and also u have created more than 10 issues. If u people create all the issues then what should we do??

**Comment by Amit366** [comment]
It's not fair in ur path.

**Comment by sairish2001** [comment]
@khareyash05 Actually @Amit366 is right from his side, as you have created a issue and more than 14 days elapsed.

**Comment by khareyash05** [comment]
Ahhh that's true..... Thank you @sairish2001 for correcting me
