### ISSUE TITLE
Circular Sector shape Calculator

### ISSUE THREAD

**Issue by madihamallick** [makesmatheasy/makesmatheasy#2902]
**Please assign this to me**

**Comment by Khushi-agarwal** [comment]
@arpit456jain can I work on this under lam-soc.

**Comment by arpit456jain** [comment]
@Khushi-agarwal let me confirm it with PA because there is no description available so i think i should ask about it once .
Will let you know soon

**Comment by sairish2001** [comment]
I think this Calculator is already there in Shapes Section.@Khushi-agarwal can you please check, if this is not there then do tell us.

**Comment by Khushi-agarwal** [comment]
@sairish2001 there is segment area calculator but I am thinking of adding this one-
![image](https://user-images.githubusercontent.com/76625662/123516361-50556680-d6b9-11eb-82ec-93f4173a45c8.png)

**Comment by sairish2001** [comment]
But please don't copy paste any image from internet, try to make it by yourself to avoid plagiarism

Go ahead
Deadline 1 July,2021

**Comment by Khushi-agarwal** [comment]
> okay fine, but please don't copy paste any image from internet, try to make it by yourself to avoid plagiarism
> 
> Go ahead
> Deadline 1 July,2021

Okay...will not do it again.
