### ISSUE TITLE
Amicable Number

### ISSUE THREAD

**Issue by shrishti-c** [makesmatheasy/makesmatheasy#3200]
A calculator to check if number is amicable or not.

I'd like to work on this.

**Comment by Khushi-agarwal** [comment]
@sairish2001 @arpit456jain can I work on this issue under lgm-soc.

**Comment by sairish2001** [comment]
Do add Steps along with Calculator
Deadline 16 July,2021

**Comment by Khushi-agarwal** [comment]
@sairish2001 lgm-soc label is not there.

**Comment by arpit456jain** [comment]
Done @Khushi-agarwal
