### ISSUE TITLE
steps to Binomial Distribution PMF Calculator

### ISSUE THREAD

**Issue by madihamallick** [makesmatheasy/makesmatheasy#3372]
**Please assign this to me**

![2](https://user-images.githubusercontent.com/70858557/119269633-46ea6180-bc16-11eb-93e8-3d2d32d60a0a.PNG)

**Comment by Khushi-agarwal** [comment]
@sairish2001 I would like to work on this.

**Comment by sairish2001** [comment]
@Khushi-agarwal Go ahead
Deadline 17 June,2021
