### ISSUE TITLE
Add steps to hamming distance

### ISSUE THREAD

**Issue by shonali2600** [makesmatheasy/makesmatheasy#3580]
I would like to add the steps

**Comment by AB-san** [comment]
#1880 issue already exists @shonali2600

**Comment by shonali2600** [comment]
@AB-san I'm so sorry I didn't see that, as this issue is so old created on May 7. 
I've created PR for this, what should I do now?

**Comment by AB-san** [comment]
> @AB-san I'm so sorry I didn't see that, as yourissue is so old created on May 7.
> I've created PR for this, what should I do now?

i have my exams going on, thats why i am not able to devote much time (thts y it tht old ) , but m still working on it.

**Comment by AB-san** [comment]
> @AB-san I'm so sorry I didn't see that, as yourissue is so old created on May 7.
> I've created PR for this, what should I do now?

@sairish2001

**Comment by shonali2600** [comment]
> > @AB-san I'm so sorry I didn't see that, as yourissue is so old created on May 7.
> > I've created PR for this, what should I do now?
> 
> i have my exams going on, thats why i am not able to devote much time (thts y it tht old ) , but m still working on it.
> you must hv checked before making issue/pr on any issue , you can do it by using the search bar near the filter in issue page

thanks for this information I'll keep this in my mind

**Comment by shonali2600** [comment]
@AB-san I just went through your all issues just now and saw that you have so many assigned issues still pending for so long and you are creating new issues. I'm not sure is it allowed or not but from my personal point of view I want to say that if you are creating huge amount of issues and not paying attention to the previously assigned issue, then how can other participant work on anything(he/she might be a beginner), because all the issues are assigned to you and no other participant is allowed to work on that.
Just a thought...

**Comment by AB-san** [comment]
> @AB-san I just went through your all issues just now and saw that you have so many assigned issues still pending for so long and you are creating new issues. I'm not sure is it allowed or not but from my personal point of view I want to say that if you are creating huge amount of issues and not paying attention to the previously assigned issue, then how can other participant work on anything(he/she might be a beginner), because all the issues are assigned to you and no other participant is allowed to work on that.
> Just a thought...

i have already asked @sairish2001  about this, as my exams are going on rn !!
