### ISSUE TITLE
pr-labeler of GitHub Action Not Working, Fixing the pr-labeler 

### ISSUE THREAD

**Issue by krishna-NIT** [makesmatheasy/makesmatheasy#4009]
## **pr-labeler of GitHub Action Not Working**

- A clear and concise description of what the bug is.

## **Replacing the .yml file**

- GitHub Action not Taking the .yml file in GitHub Action Workflow as a result. I will completely change the pr-labeler with the help of taking labeler and pr closed action. The job of this Action will be to add the GSSOC21 label on Merged PR.

**Comment by krishna-NIT** [comment]
@sairish2001 sir, Currently the Label is added manually, But this task can be automated on merged pr only. which will be helpful a lot, so Please assign me this issue!

**Comment by sairish2001** [comment]
Go ahead
Deadline 31 May,2021

**Comment by krishna-NIT** [comment]
Done @sairish2001 sir ! 👍🏻
