### ISSUE TITLE
Co-Prime number calculator

### ISSUE THREAD

**Issue by Amit366** [makesmatheasy/makesmatheasy#4126]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by Amit366** [comment]
@sairish2001 please assign it to me

**Comment by sairish2001** [comment]
Go ahead
Deadline 31 May,2021
