### ISSUE TITLE
Bug in golden and silver ratio

### ISSUE THREAD

**Issue by shonali2600** [makesmatheasy/makesmatheasy#4193]
check whether 2 numbers in silver ratio provides output at wrong place
![goldratio](https://user-images.githubusercontent.com/57946528/119979413-8af3b280-bfd8-11eb-9dc6-63e71d124f4b.png)
I would like to fix this

**Comment by abhijeet141** [comment]
@shonali2600 This issue is already there kindly check #3935

**Comment by shonali2600** [comment]
okay :)
