### ISSUE TITLE
check if a number can be expressed as sum of 2 abundant numbers is not working

### ISSUE THREAD

**Issue by shonali2600** [makesmatheasy/makesmatheasy#4197]
i would like to fix this
![2abundant](https://user-images.githubusercontent.com/57946528/119980519-04d86b80-bfda-11eb-8c43-7e64d7ab1aa3.png)

**Comment by abhijeet141** [comment]
@shonali2600 This issue is already there kindly check #3940  and please once check in the issue section before making a new issue

**Comment by shonali2600** [comment]
thanks for letting me know, actually I checked it before creating this issue, but because of so many issues it was missed. No worries I will close this issue
