### ISSUE TITLE
Automatically closing the issue when its linked PR is Merged [BOT] [GitHub Action]

### ISSUE THREAD

**Issue by krishna-NIT** [makesmatheasy/makesmatheasy#4208]
## Automatically closing the issue when its linked PR is Merged [BOT] [GitHub Action]

- After any PR is Merged, Automatically the linked Issue will also be closed. This will help the project to be more productive, It will save time as well as will control the issues as human errors will be rectified by BOT

## Adding new GitHub Action through .yml file

- A new .yml file will be added which has its code of GItHub action

**Comment by krishna-NIT** [comment]
@sairish2001 sir, Currently the issues are be closed manually after merging, But this task can be automated on merged pr only. which will be helpful a lot, so Please assign me this issue!

**Comment by krishna-NIT** [comment]
@sairish2001 please review it

**Comment by krishna-NIT** [comment]
@sairish2001 any Updates?

**Comment by sairish2001** [comment]
> @sairish2001 sir, Currently the issues are be closed manually after merging, But this task can be automated on merged pr only. which will be helpful a lot, so Please assign me this issue!

No issues are closing automatically, when prefixed with fix #issue
