### ISSUE TITLE
add convolution calculator under general maths

### ISSUE THREAD

**Issue by AB-san** [makesmatheasy/makesmatheasy#4381]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**
i wu dlike toadd it

**Comment by Khushi-agarwal** [comment]
@sairish2001 kindly assign me this issue under lgm-soc.

**Comment by arpit456jain** [comment]
Go ahead @Khushi-agarwal  
Dead line 27 June
