### ISSUE TITLE
Outlier Calculator

### ISSUE THREAD

**Issue by shrishti-c** [makesmatheasy/makesmatheasy#4419]
The Outlier Calculator to calculate the outliers of a set of numbers.

I'd like to wok on it.

**Comment by Khushi-agarwal** [comment]
@sairish2001 I would like to work on this.Please assign me under lgmsoc.

**Comment by sairish2001** [comment]
Go ahead
Deadline 19 June,2021
Do provide steps along with Calculator, fir steps use LaTeX text only, I provided the link of Katex Documentation in Slack channel
