### ISSUE TITLE
add fourstar calculator under shapes calculator 

### ISSUE THREAD

**Issue by AB-san** [makesmatheasy/makesmatheasy#4483]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

i wud like to add it

**Comment by Khushi-agarwal** [comment]
@sairish2001 can i work on this issue under lgm-soc.

**Comment by sairish2001** [comment]
Go ahead
Deadline 26 June,2021
