### ISSUE TITLE
Grammatical errors in readme 

### ISSUE THREAD

**Issue by harshita2319** [makesmatheasy/makesmatheasy#4659]
There are some grammatical errors in README.md file. 
I'd like to eliminate that.

**Comment by RakeshCharpe** [comment]
I would like to work on this issue please assign to me under LCM Soc21

**Comment by sairish2001** [comment]
Go ahead
Deadline 13 June,2021

**Comment by kshitija-2001** [comment]
I would like to work on this issue. Please assign me under LCM Soc21.

**Comment by arpit456jain** [comment]
@kshitija-2001 assigned to you please check if any other errors are still left 
Deadline 17 june

**Comment by kshitija-2001** [comment]
Ok Thank you
