### ISSUE TITLE
Bug in steps of volume of right circular cylinder in sphere

### ISSUE THREAD

**Issue by madihamallick** [makesmatheasy/makesmatheasy#4964]
**Please assign this to me**

![b1](https://user-images.githubusercontent.com/70858557/120163260-f75bf500-c216-11eb-897b-8e7665792d56.PNG)

**Comment by Simar05519** [comment]
I want to work on this issue. I am a LGM-SOC participant. Please assign to me.

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 June,2021

**Comment by Simar05519** [comment]
@sairish2001 Please give me time till 21st June as I am having my university exams going on.. I will surely complete by that time.

**Comment by sairish2001** [comment]
Deadline extended 21 June,2021

**Comment by Divyanshj** [comment]
@sairish2001 
 sir, since the deadline is vast gone, can you assign this issue to me ?

**Comment by sairish2001** [comment]
Go ahead
Deadline 9 July,2021

**Comment by Divyanshj** [comment]
@sairish2001 Sir, please extend the deadline as I will first have to add the options to the conic section, I have a created an issue for that

**Comment by sairish2001** [comment]
@Divyanshj 
Issue is closed for conic section Option, now only issue is for adding options in  General Maths. So, Deadline Extended 14 July,2021

**Comment by Divyanshj** [comment]
@arpit456jain  @sairish2001 Sir, sorry i am unable to find the correct formula for this querry , there are different answers everywhere.
According to me the formula should be 32/81 pie r^3 i.e 8/27 (volume of sphere)

**Comment by Divyanshj** [comment]
@sairish2001 Sir, please respond .

**Comment by sairish2001** [comment]
https://www.topperlearning.com/answer/find-the-volume-of-the-largest-cylinder-that-can-be-inscribed-in-a-sphere-of-radius-r-or-a-tank-with-rectangular-base-and-rectangular-sides-open-at-th/c2szmeyy

This may help
