### ISSUE TITLE
Incircle of a triangle Calculator

### ISSUE THREAD

**Issue by madihamallick** [makesmatheasy/makesmatheasy#5129]
**Please assign this to me**

**Comment by tech-rounak** [comment]
Can I contribute

**Comment by AnkitaKataria22** [comment]
pls assign me this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 16 June,2021

**Comment by AnkitaKataria22** [comment]
#include <math.h>
#include <stdio.h>
#define PI 3.14159265

// function to find area of inscribed circle
float area(float a)
{
    return (a * a * (PI / 12));
}

// function to find Perimeter of inscribed circle
float perimeter(float a)
{
    return (PI * (a / sqrt(3)));
}


int main()
{
    float a ;
    printf("Enter a: ");
    scanf("%f",&a);
    printf("Area of inscribed circle is :%f\n",
           area(a));

    printf("Perimeter of inscribed circle is :%f",
           perimeter(a));

    return 0;
}

**Comment by Khushi-agarwal** [comment]
@arpit456jain I would like to work on this issue under lgmsoc.

**Comment by arpit456jain** [comment]
ok @Khushi-agarwal assigned to you go ahead :)
Dead line 30 june
