### ISSUE TITLE
Center alignment of text inside the buttons 

### ISSUE THREAD

**Issue by Shweta200126** [makesmatheasy/makesmatheasy#5213]
## **Describe the bug**

- Text centred alignment would look better rather than being in the upper half.

## **Possible solution**

- Align the text to the centre for the buttons.

## **Screenshots**

![image](https://user-images.githubusercontent.com/72426535/120921921-e06c4580-c6e3-11eb-98ad-5450ab6d6ea4.png) 
![image](https://user-images.githubusercontent.com/72426535/120921932-ebbf7100-c6e3-11eb-8a4a-1cebffd58ee1.png)

**Comment by RakeshCharpe** [comment]
I would like to work on this issue can i work on it under LCM Soc21

**Comment by nitishapiplani** [comment]
I would like to work on it lgm SoC member

**Comment by aktamoli0910** [comment]
I would like to work on this issue under LGM-SOC-21.
