### ISSUE TITLE
Github action to add lgm-soc tag for every issues and prs created 

### ISSUE THREAD

**Issue by AB-san** [makesmatheasy/makesmatheasy#5215]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

I would like to add github actions as a participant under lgm-soc.

**Comment by AB-san** [comment]
@sairish2001 I would like to add github actions as a participant under lgm-soc. Please assign me this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 June,2021
