### ISSUE TITLE
Redesigning the Contact Us page

### ISSUE THREAD

**Issue by PranavChauhan22** [makesmatheasy/makesmatheasy#5218]
## **Is your feature request related to a problem? Please describe.**

Its not a problem.I want to basically redesign the about page as the content looks static.

## **Describe the solution you'd like**
I will change color schema by a small amount,will add animations in it and change the font style.

Please assign me this issue under lgm-soc participant

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 June,2021

**Comment by PranavChauhan22** [comment]
So admin i have completed the task,i have improved the contact form,it will work same as it was previous but now instead of directly embedding the google forms I made a form which collects data as previous and will store it in the same manner.Everything works as same as it was previously just design is changed.This is the screenshot of my work -- 
<img width="1440" alt="Screenshot 2021-06-15 at 10 15 40 PM" src="https://user-images.githubusercontent.com/83133554/122092593-b9bab700-ce27-11eb-957e-f3d31386b7d1.png">
