### ISSUE TITLE
Bug in About Page

### ISSUE THREAD

**Issue by AB-san** [makesmatheasy/makesmatheasy#5220]
## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

I guess Updated about page is loading after the old about page is displayed once

## **Screenshots**

![aboutpagebug](https://user-images.githubusercontent.com/71064674/121488075-5af0da00-c9f0-11eb-9764-e946573cd0a0.gif)

I would like to work on this under LGMSOC

**Comment by sairish2001** [comment]
Remove the old section @AB-san

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 June,2021

**Comment by AB-san** [comment]
> Remove the old section @AB-san

Ya okay ,sure

**Comment by AB-san** [comment]
> Remove the old section @AB-san

@sairish2001 I just now realized that the problem is something else.
Actually, there's a 1 second delay of CSS on about page
