### ISSUE TITLE
Many calculators are redirecting to home page when clicking on solve button

### ISSUE THREAD

**Issue by abhijeet141** [makesmatheasy/makesmatheasy#5222]
## **Describe the bug**

Many calculators are redirecting to home page when clicking on solve button

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by abhijeet141** [comment]
Please assign me this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 June,2021
