### ISSUE TITLE
Some buttons of the calculator are black and not visible!

### ISSUE THREAD

**Issue by siddhi-244** [makesmatheasy/makesmatheasy#5225]
## Proposal

I would change the button text color.

**Comment by siddhi-244** [comment]
Plzz assign it to me I am lgmsoc participant

**Comment by siddhi-244** [comment]
Sir @sairish2001  can I try it ?

**Comment by sairish2001** [comment]
Go ahead
Deadline 13 June,2021

**Comment by siddhi-244** [comment]
Ok sir

**Comment by siddhi-244** [comment]
@sairish2001 can I use text instead of the images coz I can't color images to white!
![Uploading 16234134230646852374241452904591.jpg…]()

**Comment by sairish2001** [comment]
`filter:invert(100%)`

use this, this will invert the image

**Comment by siddhi-244** [comment]
Nope it's not @sairish2001

**Comment by siddhi-244** [comment]
![16234137949761695295742951303826](https://user-images.githubusercontent.com/69195262/121684944-fd868700-cadc-11eb-99ad-214e5c977611.jpg)

This is looking better naa ? @sairish2001

**Comment by sairish2001** [comment]
try marking !important;

if still not Works, then you can use text
@siddhi-244

**Comment by siddhi-244** [comment]
Yes sir @sairish2001  but you have used text for all other buttons still I will try this method as well !

**Comment by siddhi-244** [comment]
Sir it's not working can I try text ?

**Comment by sairish2001** [comment]
> Sir it's not working can I try text ?

sure

**Comment by siddhi-244** [comment]
![16234149693253331832553194007836](https://user-images.githubusercontent.com/69195262/121687222-bb127980-cadf-11eb-9416-063fc9b8b387.jpg)
Sir @sairish2001  I am done can I generate a pull request ?

**Comment by sairish2001** [comment]
@siddhi-244 yes go ahead
