### ISSUE TITLE
To organize all the left sections 1

### ISSUE THREAD

**Issue by abhijeet141** [makesmatheasy/makesmatheasy#5226]
## **Is your feature request related to a problem? Please describe.**

To organize all the left sections  

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by abhijeet141** [comment]
I would like to work on this issue Please assign me

**Comment by sairish2001** [comment]
You Organized all the sections?

**Comment by abhijeet141** [comment]
> You Organized all the sections?

@sairish2001 I will organize all left section by today

**Comment by sairish2001** [comment]
Means all under general maths, Calculus, etc..all?

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 June,2021

**Comment by abhijeet141** [comment]
> Means all under general maths, Calculus, etc..all?

Yes :)

**Comment by sairish2001** [comment]
be make sure to use camelCase for file names
