### ISSUE TITLE
NumbersFact displayed in last

### ISSUE THREAD

**Issue by abhijeet141** [makesmatheasy/makesmatheasy#5227]
## **Describe the bug**

NumbersFact displayed in last

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![image](https://user-images.githubusercontent.com/67696867/121558348-3d912f80-ca33-11eb-8c92-06232aa093a7.png)

**Comment by abhijeet141** [comment]
I would like to work on this issue Please assign me

**Comment by arpit456jain** [comment]
Go ahead @abhijeet141

**Comment by sairish2001** [comment]
Deadline 14 June,2021
