### ISSUE TITLE
Bug in P/B/H Trio calculator

### ISSUE THREAD

**Issue by AB-san** [makesmatheasy/makesmatheasy#5229]
## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

P/B/H Trio calculator not working when perpendicular or hypotaneous is unknown

**Comment by AB-san** [comment]
Okay , lets say for ex - when I enter values of base and hypotaneous ,  value of perpendicular isn't coming out --
![image](https://user-images.githubusercontent.com/71064674/121579466-5efd1600-ca49-11eb-90a4-6c897dc464ed.png)

**Comment by arpit456jain** [comment]
ok @AB-san assigning this to you :)

**Comment by AB-san** [comment]
> @AB-san do this for base also ,
> <img alt="ss" width="960" src="https://user-images.githubusercontent.com/55352601/121580590-87394480-ca4a-11eb-8289-bc12bfc76e21.png">

Its working fine for base

**Comment by AB-san** [comment]
> ok @AB-san cool... go ahead : )
> Dead line : 15 june

Oky :)
