### ISSUE TITLE
adding hovering effect to the buttons of calculator

### ISSUE THREAD

**Issue by girija0707** [makesmatheasy/makesmatheasy#5233]

**Comment by girija0707** [comment]
please assign this issue to me I am Lgmsoc participant

**Comment by sairish2001** [comment]
Actually, In mobile phones hover effect works badly, so you can use :active instead of :hover

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 June,2021

**Comment by girija0707** [comment]
> Actually, In mobile phones hover effect works badly, so you can use :active instead of :hover

ok sir I'll do that

**Comment by girija0707** [comment]
![WhatsApp Image 2021-06-11 at 20 24 58](https://user-images.githubusercontent.com/63583646/121706447-42b5b380-caf3-11eb-9f31-ccd0676fe276.jpeg)
sir @sairish2001 is this ok?

**Comment by sairish2001** [comment]
Not looks, too good,
instead try changing box-shadow color, may be looks good

**Comment by girija0707** [comment]
> Not looks, too good,
> instead try changing box-shadow color, may be looks good

ok sir, working on it

**Comment by siddhi-244** [comment]
Sir can I try this ?

**Comment by girija0707** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/63583646/122053897-cda0f180-ce04-11eb-9cc9-2bac13940ec6.png)
@sairish2001 sir is this ok?

**Comment by sairish2001** [comment]
@girija0707 apply this Shadow effect only when the button is in :active mode

**Comment by girija0707** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/63583646/122106139-2db08b80-ce37-11eb-9d1a-3097c940ea7b.png)
sir is this fine?

**Comment by sairish2001** [comment]
https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_buttons_animate2

Apply this effect, and make a PR

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 June,2021

**Comment by siddhi-244** [comment]
Ok Sir!

**Comment by girija0707** [comment]
> just change box-shadow as `box-shadow:0 0 10px white inset;` on :active and make a PR
> sorry for inconvenience
> @girija0707

No problem sir but even I would have loved to work and make changes according to your will

**Comment by siddhi-244** [comment]
@sairish2001  the website is stuck at preloader
![20210618_115101](https://user-images.githubusercontent.com/69195262/122515764-89dc0100-d02b-11eb-80ad-c618baab01a2.jpg)

**Comment by siddhi-244** [comment]
https://user-images.githubusercontent.com/69195262/122@sairish2001 18185-826a2700-d02e-11eb-9f28-d36ac9b1fe18.mp4

Sir please check it ! @sairish2001

**Comment by siddhi-244** [comment]
https://user-images.githubusercontent.com/69195262/122518254-99a91480-d02e-11eb-832e-ac6e05f8be41.mp4

Sir @sairish2001 is it okayy ?? I have added box shadow and border radius
