### ISSUE TITLE
Add a restart button in the setting 

### ISSUE THREAD

**Issue by tjanhvi** [makesmatheasy/makesmatheasy#5238]
Want to add a restart button after the line "Kindly restart the app to apply changes" 
Please assign me this issue.

**Comment by tjanhvi** [comment]
> Hi 😄, thanks for creating your first issue at makemathseasy, do read and follow the [Code of Conduct](https://github.com/sairish2001/makesmatheasy/blob/main/CODE_OF_CONDUCT.md) and the [Contribution Guidelines](https://github.com/sairish2001/makesmatheasy/blob/main/CONTRIBUTING.md) while contributing.

okay :)
please assign me this issue

**Comment by arpit456jain** [comment]
go ahead @tjanhvi :)
Deadline 16 June 2021

**Comment by tjanhvi** [comment]
okay :)
