### ISSUE TITLE
Change the home page look

### ISSUE THREAD

**Issue by tjanhvi** [makesmatheasy/makesmatheasy#5239]
Want to make the home page more creative like by adding background etc.

**Comment by tjanhvi** [comment]
> Hi 😄, @tjanhvi Thanks for creating issue at makemathseasy, do read and follow the [Code of Conduct](https://github.com/sairish2001/makesmatheasy/blob/main/CODE_OF_CONDUCT.md) and the [Contribution Guidelines](https://github.com/sairish2001/makesmatheasy/blob/main/CONTRIBUTING.md) while contributing.

okay :)

**Comment by tjanhvi** [comment]
Please assign me this issue

**Comment by nitishapiplani** [comment]
hey i would like to work on this issue plzz assign lgmsoc participant

**Comment by arpit456jain** [comment]
hey @nitishapiplani we have to follow the first come first serve rule so that's why i have to assign this issue to @tjanhvi .
if she is unable to complete this issue before the deadline then i will assign it to you. :)

**Comment by arpit456jain** [comment]
go ahead :) 
DeadLine 17 june

**Comment by nitishapiplani** [comment]
> hey @nitishapiplani we have to follow the first come first serve rule so that's why i have to assign this issue to @tjanhvi .
> if she is unable to complete this issue before the deadline then i will assign it to you. :)

Okkay

**Comment by sairish2001** [comment]
@nitishapiplani Till then explore the Project, or there are too many issues Open, even if it's labeled as GSSOC are open to work.
or you can create your own issue, and ask for assignment
