### ISSUE TITLE
Text not visible in Euclid Geometry section

### ISSUE THREAD

**Issue by Sukhseerat-Kaur** [makesmatheasy/makesmatheasy#5242]
## **Describe the bug**

In the euclid geometry section, axioms and postulates are in black colour which is not readable.

## **Possible solution**

Let me change the colour of the text.

## **Screenshots**
![Screenshot (111)](https://user-images.githubusercontent.com/54837213/121770275-0a12ea00-cb86-11eb-9687-6306a17f8a62.png)

**Comment by Sukhseerat-Kaur** [comment]
@sairish2001 Please assign me this under LGMSOC'21

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 June,2021
