### ISSUE TITLE
2 different icons for favourites makes it confusing.

### ISSUE THREAD

**Issue by Sukhseerat-Kaur** [makesmatheasy/makesmatheasy#5243]
## **Describe the bug**

The icon for for adding any section to favourites in the side bar is that of a heart but the icon on the right side is of a star. This makes it confusing for users to find the favourites section as they might hunt for the heart icon.

## **Possible solution**

Let me make the icon uniform. All should be either hearts or stars.

## **Screenshots**
![Screenshot (113)_LI](https://user-images.githubusercontent.com/54837213/121770613-e6e93a00-cb87-11eb-81b9-ab69a846c411.jpg)

**Comment by Sukhseerat-Kaur** [comment]
@sairish2001 Please assign me this under LGMSOC'21

**Comment by sairish2001** [comment]
No, on clicking the heart the Calculator is marked as favourite, which you can access directly through button on the home screen

**Comment by sairish2001** [comment]
Both are different

**Comment by sairish2001** [comment]
Go ahead
Deadline 14 June,2021
