### ISSUE TITLE
add a temperature convertor in the basic convertor section.

### ISSUE THREAD

**Issue by jugeshraghav** [makesmatheasy/makesmatheasy#5244]
## **Is your feature request related to a problem? Please describe.**

- A temperature convertor from degree celsius to fahrenheit and vice-versa.

## **Describe the solution you'd like**

if a temperature is given in degree celsius we can convert it to fahrenheit and vice versa is also possible.

**Comment by jugeshraghav** [comment]
Please assign this issue to me.

**Comment by sairish2001** [comment]
Temperature converter is already there, you can explore the project, or have a look to other Open Issues, even though they labelled as GSSOC, still they are open to work
