### ISSUE TITLE
Principle of Mathematical Induction (PMI)

### ISSUE THREAD

**Issue by ROHAN842** [makesmatheasy/makesmatheasy#5245]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by ROHAN842** [comment]
please assign this issue to me under LGMSOC

**Comment by sairish2001** [comment]
Go ahead
Deadline 17 June,2021

**Comment by ROHAN842** [comment]
OK

**Comment by arpit456jain** [comment]
@ROHAN842 any updates ?

**Comment by Divyanshj** [comment]
@sairish2001 Sir , since it has been 3 days after the deadline and there are no updates, can you assign this issue to me?

**Comment by arpit456jain** [comment]
ok @Divyanshj assigning this issue to you :) 
Go ahead 
dead line 27 june

**Comment by Divyanshj** [comment]
@arpit456jain Should I add PMI as a separate topic like conic section or should I add it as a subtopic under one of the topics(which one should it be)?

**Comment by sairish2001** [comment]
@Divyanshj can you please tell what you are going to add in this?

**Comment by Divyanshj** [comment]
@sairish2001 Sir,as PMI i used to prove eqns I cannot display the andwer for every eqn .
What i was thinking is that I will create 3 subtopics in it
1)intro - it will tell what is PMI , what is it used for and it's pupose
2) steps- it will display all the steps which you have to apply in every eqn to solve (stepwise)
3) proof- it will display how after applying these steps we can say that the given eqn is true (confirmation)

**Comment by sairish2001** [comment]
@Divyanshj 
Actually we are planning to remove the theory part, except identities, but if you use your own language, i.e without copy/pasting from any other website, then only we can accept it. as one of the major reason behind removing the theory part is plagiarism. That's why.

**Comment by Divyanshj** [comment]
@sairish2001 
Sir correct me if i am wrong, what I think is that the steps about which I was talking are indentities in themselves as every person will have to use those identities/steps in every question of PMI. 
Basically, these steps are the identities or formulas for PMI (universally).
Also, I will try to write max of the content in my own language instead of copying it from somewhere else and make it more understandable.

**Comment by sairish2001** [comment]
@Divyanshj Fine! Go ahead

**Comment by Divyanshj** [comment]
> @arpit456jain Should I add PMI as a separate topic like conic section or should I add it as a subtopic under one of the topics(which one should it be)?

@sairish2001 Sir , what should I do ?

**Comment by sairish2001** [comment]
Make a new option @Divyanshj
