### ISSUE TITLE
trigoformula.html

### ISSUE THREAD

**Issue by akash435** [makesmatheasy/makesmatheasy#5246]
Want to add all the basics to advanced trigo formulas and identities.
and this will be under the study section of project.

**Comment by akash435** [comment]
@sairish2001 , please assign this to me under LGM SOC , As i want to contribute under it

**Comment by sairish2001** [comment]
Go ahead
Deadline 16 June,2021

**Comment by akash435** [comment]
Thanks for assigning me

**Comment by akash435** [comment]
@sairish2001 , I created a pr related to this issue , please check it.
