### ISSUE TITLE
I would like to add type of equations section in the equation section.

### ISSUE THREAD

**Issue by jugeshraghav** [makesmatheasy/makesmatheasy#5247]
## **Is your feature request related to a problem? Please describe.**

-There are  many types of equations and I think we should mention each of them .

## **Describe the solution you'd like**

-Equations are classified on the basis of their degree and no of terms. I think we must include types of equations section in the equation section.

**Comment by sairish2001** [comment]
Can you please share some, examples, which type of equations you talking about

**Comment by jugeshraghav** [comment]
Equations are classified into two types:
1.On the basis of degree:
a.linear
b.Quadratic
c.cubic
2.On the basis of no of terms:
a. monomial
2. Some other types of equations are :
a.Radical
b..exponential
c.rational

**Comment by sairish2001** [comment]
Go ahead
Deadline 17 June,2021

**Comment by sairish2001** [comment]
Actually we are planning to remove the study section from the Project.
But only identities part remains in, i.e. section which contains identies.

**Comment by jugeshraghav** [comment]
Okay
