### ISSUE TITLE
Linear system of algebraic equations

### ISSUE THREAD

**Issue by akash435** [makesmatheasy/makesmatheasy#5249]
Want to add all the methods to solve the linear system of algebraic Equation.
Different methods include,
i.) Direct Method
     Cramer's rule
     Gauss Elimination methoid
     Gauss Jordan method
     Factorization Method 
     Cholesky Method
ii.) Indirect Method
     Jacobi method
     Gauss seidel method

I want to add the basic theory and formula with explaination of each methods.

**Comment by akash435** [comment]
@sairish2001 , please assign this to me under LGM SOC , want to add this topic under study section

**Comment by sairish2001** [comment]
Actually we are planning to remove the study section from the Project.
But only identities part remains in, i.e. section which contains identies.
