### ISSUE TITLE
calculate speed of a vehicle from given distance and time in the general maths section.

### ISSUE THREAD

**Issue by jugeshraghav** [makesmatheasy/makesmatheasy#5254]

**Comment by arpit456jain** [comment]
ok @jugeshraghav assigning to you 
dead line 17 june

**Comment by jugeshraghav** [comment]
Thank you @arpit456jain

**Comment by sairish2001** [comment]
Do provide steps for the same, if you can. We are using LaTex text for showing steps, We have sent a link of documentation of Katex support table in our Slack Channel

**Comment by jugeshraghav** [comment]
Sure I will do that.

**Comment by arpit456jain** [comment]
@jugeshraghav any updates ?

**Comment by jugeshraghav** [comment]
I will give updates till tommorow morning actually I have semester exams.

**Comment by arpit456jain** [comment]
ok @jugeshraghav

**Comment by jugeshraghav** [comment]
Thank you so much

**Comment by jugeshraghav** [comment]
@arpit456jain I need a help , the calculator is to be placed in the calculator section or there is any other section for general maths.

**Comment by sairish2001** [comment]
@jugeshraghav You need to place .html file into the Calculators folder

**Comment by jugeshraghav** [comment]
okay how to i write css and js code for it . I looked in several files there is only html code written for them and what do i do to write logics.

**Comment by sairish2001** [comment]
we are planning to release it as a library also, so place logic for functions in 
library/logicjavascript.js file

and for css just add class to the fields, for test purpose you can call 

loadcalculator ('filename') on window load

for calling the function which you defined in logicjavascript.js file use script tag in file you will create in Calculators folder.


for more clarity see magicNumber.html file and logic for it in logicjavascript.js file

**Comment by jugeshraghav** [comment]
okay, thank you so much @sairish2001

**Comment by jugeshraghav** [comment]
what is the final label of this issue . I am confused.

**Comment by arpit456jain** [comment]
level 2 @jugeshraghav  you can check it on right side on top

**Comment by jugeshraghav** [comment]
Thanks, I'll check it out.
