### ISSUE TITLE
Add copy functionality to the facts

### ISSUE THREAD

**Issue by utkarshgoel10** [makesmatheasy/makesmatheasy#5256]
## **Is your feature request related to a problem? Please describe.**

- Since, you are providing such awesome facts, it would be great if users could just copy that text and keep it with them. 

## **Describe the solution you'd like**

- Now, instead of manually selecting and then copying the text, we can add functionality through which if the user just clicks on the fact dialog box the text would be copied to their clipboard.

**Comment by utkarshgoel10** [comment]
Please assign this issue to me

**Comment by sairish2001** [comment]
@utkarshgoel10 I think there's no need of this. it's very rare the user wants to copy facts
