### ISSUE TITLE
Number not visible on user input for Mean Calculator(AM GM &HM) and for Sum of N terms AP, GP, HP

### ISSUE THREAD

**Issue by ROHAN842** [makesmatheasy/makesmatheasy#5257]
## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by ROHAN842** [comment]
please assign this issue to me under LGMSOC

**Comment by ROHAN842** [comment]
when ever user types any sort of number in linear algebra section under Mean Calculator(AM GM &HM) and for Sum of N terms AP, GP, HP in the calculator then it is not visible to user as it is in black color I think it should be in white as per the dark background

**Comment by arpit456jain** [comment]
ok @ROHAN842 assigning this you go ahead :)
Dead line 18 june

**Comment by ROHAN842** [comment]
OK
