### ISSUE TITLE
Add Code of Conduct and License in Readme File

### ISSUE THREAD

**Issue by Shaishav0507** [makesmatheasy/makesmatheasy#5259]
Hey @arpit456jain @sairish2001 
I would like to add code of conduct and license in readme file.
Please assign it to me.
Thanks

**Comment by arpit456jain** [comment]
@Shaishav0507 Its already there no need to mentioning  it into read me . I hope you understand  you can explore other issues as well even if it has a gssoc label :) we will change it to LGSM label
