### ISSUE TITLE
I would like to replace the Plagrised code 

### ISSUE THREAD

**Issue by abhijeet141** [makesmatheasy/makesmatheasy#5260]
## **Describe the bug**

I would like to replace the Plagrised code 

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by abhijeet141** [comment]
Please assign me this issue

**Comment by arpit456jain** [comment]
ok @abhijeet141 assigning this to you Go ahead :)
Dead line 19 june
