### ISSUE TITLE
New Topic Mensuration should be added

### ISSUE THREAD

**Issue by tanya070820** [makesmatheasy/makesmatheasy#5266]
## **Is your feature request related to a problem? Please describe.**

-I want to add mensuration related formulas which cover 2D and 3D shapes(cylinder ,circle,polygon,etc)

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by sairish2001** [comment]
Can you explain a little, that you want to create Calculators or just want to add formulas?

**Comment by tanya070820** [comment]
I want to add mensuration formulas in it @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 20 June,2021

**Comment by Divyanshj** [comment]
@sairish2001 Sir, since the deadline is over , can you assign this issue to me  ?

**Comment by sairish2001** [comment]
Go ahead
Deadline 26 June,2021

**Comment by Divyanshj** [comment]
@sairish2001 Sir, the formulas must come on the right hand side pane of the website in the same theme or should i direct them to a new html page after clicking on any of the mensuration topic.
![image](https://user-images.githubusercontent.com/72750492/122745462-a899fc00-d2a6-11eb-9a37-7c385d7cbfb9.png)

**Comment by sairish2001** [comment]
You just need to call loadcalculator function onclick, as we did for other Calculators

**Comment by Divyanshj** [comment]
@sairish2001 , yes i get that but first I have to create topic wise html pages for mensuration topic to put in the onclick function, right ?

**Comment by sairish2001** [comment]
> @sairish2001 , yes i get that but first I have to create topic wise html pages for mensuration topic to put in the onclick function, right ?
>  

Yes

**Comment by Divyanshj** [comment]
@sairish2001 Sir, i have a linked a PR for this issue and have explained everything in it.
