### ISSUE TITLE
Steps for distance between Excentre and Circumcentre

### ISSUE THREAD

**Issue by jasminekaur-prog** [makesmatheasy/makesmatheasy#5270]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by jasminekaur-prog** [comment]
@sairish2001  Assign this issue to me

**Comment by sairish2001** [comment]
Go ahead
Deadline 20 June,2021
