### ISSUE TITLE
Missing Reset Button

### ISSUE THREAD

**Issue by Sukhseerat-Kaur** [makesmatheasy/makesmatheasy#5276]
## **Describe the bug**

Reset button is missing from Nth term of Ruler Function series calculator under Important Series and Sequences section.

## **Possible solution**

Let me fix add the button and assign me this under LGMSoC'21

## **Screenshots**

![image](https://user-images.githubusercontent.com/54837213/122249871-d5d15d80-cee6-11eb-8e3b-1fa20b83e9a4.png)

**Comment by arpit456jain** [comment]
Ok @Sukhseerat-Kaur assigning to you go ahead 
Dead line 20 june

**Comment by sairish2001** [comment]
@Sukhseerat-Kaur Any updates?

**Comment by Sukhseerat-Kaur** [comment]
> @Sukhseerat-Kaur Any updates?

PR will be opened by today itself. Sorry for the delay
