### ISSUE TITLE
LCM and HCF.

### ISSUE THREAD

**Issue by deepaahuja92** [makesmatheasy/makesmatheasy#5277]
## Proposal

I would like to include the function for finding LCM and HCF by taking two numbers under the linear algebra section.Please assign me this issue.I would like to work on this issue under LGMSOC'21

**Comment by sairish2001** [comment]
@ishitakapoor26 This is already there in the Linear Algebra section or I think in General Maths Section, so no need of adding

**Comment by deepaahuja92** [comment]
Okay.
