### ISSUE TITLE
Add LGM-SOC'21 score card in readme.md

### ISSUE THREAD

**Issue by ishitakapoor26** [makesmatheasy/makesmatheasy#5278]
Add LGM-SOC'21 score card in readme.md

**Comment by ishitakapoor26** [comment]
@arpit456jain pls assign this issue to me.

**Comment by arpit456jain** [comment]
@sairish2001 will decide whether its needed or not .
He will assign you soon if its needed

**Comment by ishitakapoor26** [comment]
> @sairish2001 will decide whether its needed or not .
> He will assign you soon if its needed
> 
> Meanwhile you can explore the other open issues and if you think you can do it just mention me and i will assign it you 🙂

okay but pls inform me if you @sairish2001 wants it to be added.

**Comment by sairish2001** [comment]
@ishitakapoor26 This is already there in the Linear Algebra section or I think in General Maths Section, so no need of adding
