### ISSUE TITLE
To organize section 3

### ISSUE THREAD

**Issue by abhijeet141** [makesmatheasy/makesmatheasy#5280]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by abhijeet141** [comment]
@sairish2001 kindly assign me

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 June,2021
