### ISSUE TITLE
Organize Sections

### ISSUE THREAD

**Issue by deepaahuja92** [makesmatheasy/makesmatheasy#5281]
I would like to organize the section of index.html file by removing the calculators from them and making new files for them and them there.I would like to do this as a part of LGMSOC'21 . Please assign this issue to me.

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 June,2021

**Comment by sairish2001** [comment]
Actually we are planning to remove the study Section, i.e which contains only theory part no Calculator. So leave them organize only Calculators sections

**Comment by deepaahuja92** [comment]
so should I delete the theory part?

**Comment by abhijeet141** [comment]
@deepaahuja9 Most of the calculators are organized only Trigonometry sections calculator and half calculators of General Math sections are left you can organize them

**Comment by sairish2001** [comment]
> so should I delete the theory part?or should remain as it is...only I have to work upon calculators section.

Leave them, as I need to go through the study Section first, so organize only Sections which is calculating something

**Comment by sairish2001** [comment]
@deepaahuja92  Any Updates?

**Comment by deepaahuja92** [comment]
No...I was busy so unable to do but tomorrow I will surely make commit.

**Comment by sairish2001** [comment]
Will you be able to complete it by tomorrow, as Deadline is near?@deepaahuja92

**Comment by deepaahuja92** [comment]
I will be needing more time to work on this as because of some work I was
not able to do.

**Comment by sairish2001** [comment]
How much time?

**Comment by deepaahuja92** [comment]
Till 25th

**Comment by sairish2001** [comment]
Deadline extended 25 June,2021

**Comment by sairish2001** [comment]
@deepaahuja92 Any updates, as deadline is near. If you are not comfortable while solving this Do tell us, no worries.

**Comment by deepaahuja92** [comment]
I am really sorry sir.Because of rainy season the electricity is not there
is my home for maximum time.So my pc is not charged and also there is no
internet because of no electricity my modem does not work. So that's the
only problem because of which I am not able to do the work,Please can you
assign it to someone else?I am again very sorry.

**Comment by sairish2001** [comment]
No problem @deepaahuja92

**Comment by coding-geek21** [comment]
i would like to work on this please assign me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 27 June,2021

**Comment by sairish2001** [comment]
@coding-geek21 Any updates?

**Comment by sairish2001** [comment]
@coding-geek21 Any updates, as deadline is near?

**Comment by coding-geek21** [comment]
> @coding-geek21 Any updates, as deadline is near?
> If you are not comfortable with this issue, do tell us, feel free

Can you please extend the deadline? Since my exams are nearing..
If anyone is going to work on this issue let them work otherwise can I resume my work after exams?

**Comment by sairish2001** [comment]
@coding-geek21 Actually the whole base of project is based on this issue, I want to solve this as soon as possible.
So I am unassigning you @coding-geek21 Sorry!

But after exams come back with more energy 🔥

**Comment by abhijeet141** [comment]
@sairish2001 I want to work on this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 1 July,2021

**Comment by coding-geek21** [comment]
> @coding-geek21 Actually the whole base of project is based on this issue, I want to solve this as soon as possible.
> So I am unassigning you @coding-geek21 Sorry!
> 
> But after exams come back with more energy 🔥

Sure !
