### ISSUE TITLE
Modify Happy Number Function to Library Function

### ISSUE THREAD

**Issue by jasminekaur-prog** [makesmatheasy/makesmatheasy#5290]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by jasminekaur-prog** [comment]
@sairish2001 Please assign me this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 22 June,2021
