### ISSUE TITLE
Reset not working as expected

### ISSUE THREAD

**Issue by Sukhseerat-Kaur** [makesmatheasy/makesmatheasy#5293]
## **Describe the bug**

As can be seen in the attached video, the Reset button under Sum of Sequence x,xx,xxx Calculator loads the whole web-app again. But it is not as expected as all the other Reset buttons only reset the value in their respective input fields.

## **Possible solution**

Let me fix this under LGMSOC'21

## **Screenshots**
[Makes Math Easy - Google Chrome 2021-06-20 20-16-08.zip](https://github.com/makesmatheasy/makesmatheasy/files/6682543/Makes.Math.Easy.-.Google.Chrome.2021-06-20.20-16-08.zip)

**Comment by sairish2001** [comment]
No need to create another issue, just make a commit in your existing branch from which you made a PR

**Comment by Sukhseerat-Kaur** [comment]
> No need to create another issue, just make a commit in your existing branch from which you made a PR

Ok committed. So just had to commit and push in the branch ryt? No need to open a PR for this issue?

**Comment by sairish2001** [comment]
> > No need to create another issue, just make a commit in your existing branch from which you made a PR
> 
> Ok committed. So just had to commit and push in the branch ryt? No need to open a PR for this issue?

Exactly
