### ISSUE TITLE
Modify Perfect Value function into Library function 

### ISSUE THREAD

**Issue by jasminekaur-prog** [makesmatheasy/makesmatheasy#5295]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by jasminekaur-prog** [comment]
@sairish2001 Please assign me this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 26 June,2021

**Comment by arpit456jain** [comment]
any updates @jasminekaur-prog ?

**Comment by jasminekaur-prog** [comment]
already did it issue #5298

**Comment by arpit456jain** [comment]
ok sorry for inconvenience

**Comment by jasminekaur-prog** [comment]
@arpit456jain No problem
