### ISSUE TITLE
I would like to add particle.js in the background

### ISSUE THREAD

**Issue by abhijeet141** [makesmatheasy/makesmatheasy#5300]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by abhijeet141** [comment]
@sairish2001 @arpit456jain  Kindly assign this issue to me i would like to give a try and if it looks good than you can merge it

**Comment by sairish2001** [comment]
Okay fine!
You can give a try on newdesign.html page
Deadline 27 June,2021
