### ISSUE TITLE
add some badges and make them of single type

### ISSUE THREAD

**Issue by Umesh-01** [makesmatheasy/makesmatheasy#5303]
## **Is your feature request related to a problem? Please describe.**

I will add some more badges to the top of readme.md file and make them of single type so that it will look more interactive and awesome, since the badges will be colorful and more attractive than the text the users will like it and it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

See this image, the badge are of different type...

![image](https://user-images.githubusercontent.com/83420185/122971488-bafe5d80-d3ac-11eb-8c39-1c99014d5c78.png)

## **Describe the solution you'd like**

- I will align them to the center
- I will add some more badges
- I will add links to the badges
- I will make them all of single type

**Comment by sairish2001** [comment]
Go ahead
Deadline 27 June,2021
