### ISSUE TITLE
I would like to add time and distance calculate feature in the speed calculator.

### ISSUE THREAD

**Issue by jugeshraghav** [makesmatheasy/makesmatheasy#5304]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by jugeshraghav** [comment]
i would like to work on the issue.

**Comment by arpit456jain** [comment]
@jugeshraghav can you do some thing like what we have on P/B/H trigo 
like if 3 input fields are there , distance , time , speed
if user enter 2 of them it should show the 3rd one

**Comment by jugeshraghav** [comment]
Ya I would

**Comment by arpit456jain** [comment]
Ok then go ahead @jugeshraghav

**Comment by arpit456jain** [comment]
Deadline 28 june

**Comment by jugeshraghav** [comment]
the issue is completed so i am closing this issue. Thank you so much @arpit456jain @sairish2001 you helped me a lot.
