### ISSUE TITLE
Large Calculator

### ISSUE THREAD

**Issue by surbhi594** [makesmatheasy/makesmatheasy#5305]
When I'm trying to open the calculator, the size of the calculator is coming large and the whole calculator is not visible even after scrolling the window.
Please assign this issue to me under LGMSOC'21.

![Screenshot (110)](https://user-images.githubusercontent.com/71223742/123099496-dec6af80-d44f-11eb-84e7-c3abef9a6f4f.png)

**Comment by sairish2001** [comment]
One thing you can do, make a separate file as we did for other Calculators, and load this file using loadcalculator function in newdesign.html page

Calculator should be loaded when we click on center button( logo of makes math easy)

and after creating new file make it responsive

**Comment by surbhi594** [comment]
Okay, @sairish2001 I will try it and if any problem arises I will contact you regarding that.

**Comment by sairish2001** [comment]
Deadline 28 June,2021

**Comment by surbhi594** [comment]
@sairish2001, can you please extend the deadline till 30th June as my exams are going on

**Comment by sairish2001** [comment]
Deadline extended 1 July,2021
