### ISSUE TITLE
Enhance the contact us page

### ISSUE THREAD

**Issue by coding-geek21** [makesmatheasy/makesmatheasy#5309]
## **Is your feature request related to a problem? Please describe.**

Enhance the contact us page, the contact us page looks dull and the text boxes are not clearly visible i would like to enhance this
please assign me under lgm-soc'2021

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by arpit456jain** [comment]
go ahead @coding-geek21 .
Dead line 29 june
