### ISSUE TITLE
Several error and rules changes in root of equation

### ISSUE THREAD

**Issue by stymm-1** [makesmatheasy/makesmatheasy#5315]
Issues:
1. Below 
    Nature of roots, at the 2nd point it should be only '>' instead of '>='.
2. In rules section, the colour of heading should be darker as it is not much visible.
3. In rules section, In the first rule there is a '<' sign missing.
4. In rules section, Second rule- more appropriate statement can be used i.e
    instead of  'There is one real root if' we can write 'There are two equal real roots if'
I would like to work on this issue.

![Screenshot 2021-06-25 020406](https://user-images.githubusercontent.com/64557006/123328815-add2a180-d559-11eb-9250-188d5089387d.png)

**Comment by stymm-1** [comment]
Can I work on this?

**Comment by arpit456jain** [comment]
yes @stymm-1 go ahead :)
Dead line 30 june
