### ISSUE TITLE
Some calculators name under 3D shapes are not visible

### ISSUE THREAD

**Issue by abhijeet141** [makesmatheasy/makesmatheasy#5318]
## **Describe the bug**

Some calculators name under 3D shapes are not visible

## **Screenshots**

![image](https://user-images.githubusercontent.com/67696867/123443098-34878d00-d5f3-11eb-95c3-add046912bf4.png)

**Comment by arpit456jain** [comment]
go ahead @abhijeet141 :)
Dead line 30 june
