### ISSUE TITLE
Can I create a temperature converter which includes celcius, fahrenheit and kelvin conversions. 

### ISSUE THREAD

**Issue by jugeshraghav** [makesmatheasy/makesmatheasy#5322]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by jugeshraghav** [comment]
I would like to work on this issue.

**Comment by abhijeet141** [comment]
@jugeshraghav It is already present in unit convertor

**Comment by sairish2001** [comment]
@jugeshraghav this is already present in Unit Converters Section
