### ISSUE TITLE
Add hovering effects on the calculator icon 

### ISSUE THREAD

**Issue by siddhi-244** [makesmatheasy/makesmatheasy#5325]
## **Is your feature request related to a problem? Please describe.**

I would like to add hovering effect to the calculator icon. Image is given below.
## **Describe the solution you'd like**

- I would change the box-shadow,background color,border etc to the icon.
![Screenshot_20210627-125515_Chrome](https://user-images.githubusercontent.com/69195262/123536328-467a4480-d747-11eb-9602-624b1cbe21ea.jpg)

**Comment by siddhi-244** [comment]
Plzz assign me this under lgmsoc

**Comment by sairish2001** [comment]
As soon we will be shifting to new UI, so no need for it.
Sorry for it UI will be changed within 2 days from now
