### ISSUE TITLE
Changes required in about.html

### ISSUE THREAD

**Issue by puneetkaur2929** [makesmatheasy/makesmatheasy#5330]
Hey @sairish2001 
As you can see Home and contact us buttons in about.html are not properly visible . Moreover custom scroller is not easily identifiable .

I am interested to work on this issue under LGM SOC 21
Kindly assign this issue to me.
![Screenshot (54)](https://user-images.githubusercontent.com/80326308/123686758-c8648d80-d86d-11eb-9600-4c5089362a3e.png)

**Comment by sairish2001** [comment]
Go ahead
Deadline 3 July,2021
