### ISSUE TITLE
Changes in setting section

### ISSUE THREAD

**Issue by stymm-1** [makesmatheasy/makesmatheasy#5331]
Issue :
1. Heading is not visible.
2. No need of horizontal lines.
3.  Restart statement should be small as a hint.
![Screenshot 2021-06-29 122405](https://user-images.githubusercontent.com/64557006/123752005-01384d00-d8d6-11eb-8dcc-08530ccad399.png)

**Comment by stymm-1** [comment]
I would like to work on this. Please assign this to me.

**Comment by sairish2001** [comment]
Thanks for showing interest in this project, but today the UI of Project will be changed, so this problem will be fixed. No need for this.
