### ISSUE TITLE
Add options in Basic Converters page

### ISSUE THREAD

**Issue by sairish2001** [makesmatheasy/makesmatheasy#5332]
As did in `appdata/menudata/linearAlgebra.html ` page, 
add options in `appdata/menudata/basicConverters.html` page in similar way.

You can check these options in `old.html file`

**Comment by Khushi-agarwal** [comment]
@sairish2001 I would like to work on it.

**Comment by sairish2001** [comment]
Go ahead
Deadline 5 July,2021

**Comment by Khushi-agarwal** [comment]
@sairish2001 what to do with those calculators who do not have html file loaded in the old.html

**Comment by sairish2001** [comment]
Means which don't have loadcalculator() function?
or how they placed, as a Modal Popup?

**Comment by Khushi-agarwal** [comment]
> Means which don't have loadcalculator() function?
> or how they placed, as a Modal Popup?

which don't have loadcalclator() function

**Comment by sairish2001** [comment]
can you please share a screenshot!

**Comment by sairish2001** [comment]
@Khushi-agarwal Instead of onclick=loadcalculator(), just add 

`data-toggle and data-target` part as it's a modal

**Comment by sairish2001** [comment]
and one More thing just add 🔴 this emoji ,where there's a modal, as we need are planning to change modals to simple page Calculators, so it would be helpful in future to identify the modal Calculator.

Like Name is 
Conversion to Words🔴

**Comment by Khushi-agarwal** [comment]
Okay!!
