### ISSUE TITLE
Change the text highlighting color

### ISSUE THREAD

**Issue by UG-SEP** [makesmatheasy/makesmatheasy#5343]
## **Is your feature request related to a problem? Please describe.**

When I select text it hides the text it is because I think the text highlighting color is black and the background color is also black so the text hides

## **Describe the solution you'd like**

Change the text highlighting color the appropriative one i.e. light,blue,light cyan, etc

**Comment by arpit456jain** [comment]
hey @UG-SEP please be specific where this problem is occurring or share some screen shots or videos

**Comment by UG-SEP** [comment]
# before
![before](https://user-images.githubusercontent.com/75884061/124279610-576eef80-db65-11eb-9882-0d79a272af94.jpg)
# After i selected the written text
![after](https://user-images.githubusercontent.com/75884061/124279667-65bd0b80-db65-11eb-83d1-a55f275af579.jpg)

**Comment by arpit456jain** [comment]
ok @UG-SEP go ahead :)
Dead line 2 july
