### ISSUE TITLE
Can I make a footer for the website.

### ISSUE THREAD

**Issue by jugeshraghav** [makesmatheasy/makesmatheasy#5346]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by jugeshraghav** [comment]
I would like to work on the issue.

**Comment by arpit456jain** [comment]
@sairish2001 do we need a footer? Please Have a look on this issue

**Comment by sairish2001** [comment]
It's more likely a webapp, rather than website, so no need of any footer.
Thanks
