### ISSUE TITLE
Add options in conic.html

### ISSUE THREAD

**Issue by Khushi-agarwal** [makesmatheasy/makesmatheasy#5350]
## **Is your feature request related to a problem? Please describe.**

@sairish2001 kindly assign me this issue under lgmsoc

**Comment by sairish2001** [comment]
Go ahead
Deadline 9 July,2021

**Comment by sairish2001** [comment]
@Khushi-agarwal Any Updates?

**Comment by Khushi-agarwal** [comment]
> @Khushi-agarwal Any Updates?
It will be done by eod
