### ISSUE TITLE
Add cursor pointer to search button

### ISSUE THREAD

**Issue by supzi-del** [makesmatheasy/makesmatheasy#5359]
## **Is your feature request related to a problem? Please describe.**

- When search button on homepage is hovered, cursor should be pointer.

## **Describe the solution you'd like**

- Same as above.

**Comment by supzi-del** [comment]
I want to work on this under LGMSOC.

**Comment by arpit456jain** [comment]
@supzi-del go ahead 
Dead line 13 july

**Comment by supzi-del** [comment]
Hey , I am having some issues with making a PR. Please assign this to someone else.

**Comment by arpit456jain** [comment]
Hey @supzi-del you can share your problem with us may be we can help.....
Otherwise no problem 🙌 you can simply un assign yourself.

**Comment by supzi-del** [comment]
![image](https://user-images.githubusercontent.com/78655439/125173726-474ab600-e1de-11eb-8798-26f55c71139d.png)

**Comment by supzi-del** [comment]
I want to make a PR only with the last commit, I'm not sure why other commits from other issues are coming up.

**Comment by arpit456jain** [comment]
Did you make a new branch after clonning the repo ?

**Comment by supzi-del** [comment]
> Did you make a new branch after clonning the repo ?

Yes

**Comment by arpit456jain** [comment]
Ok make a PR will see what's the problem
