### ISSUE TITLE
Adding options in conic.html 

### ISSUE THREAD

**Issue by Divyanshj** [makesmatheasy/makesmatheasy#5365]
## **Describe the bug**

there is nothing inside the conic section tab

## **Screenshots**

![image](https://user-images.githubusercontent.com/72750492/125172265-59c0f180-e1d6-11eb-9de2-2fcd77b98624.png)

**Comment by Divyanshj** [comment]
@sairish2001 please assign this issue to me under LGM-SOC'21

**Comment by sairish2001** [comment]
Options in Conic section is already there!
Update your codebase

![Screenshot_20210710-233140_Brave.jpg](https://user-images.githubusercontent.com/60106112/125172368-00a58d80-e1d7-11eb-9028-c35d22bc75ae.jpg)

**Comment by Divyanshj** [comment]
@sairish2001 Updated sir, sorry for that !

**Comment by sairish2001** [comment]
> @sairish2001 Updated sir, sorry for that !
> 

No Worries
