### ISSUE TITLE
Adding options in generalMaths.html

### ISSUE THREAD

**Issue by Divyanshj** [makesmatheasy/makesmatheasy#5366]
## **Is your feature request related to a problem? Please describe.**

There is nothing inside general maths section

**Comment by Divyanshj** [comment]
@sairish2001 please assign this issue to me under LGM-SOC'21

**Comment by sairish2001** [comment]
Go ahead
Deadline 16 June,2021

**Comment by Divyanshj** [comment]
@sairish2001 Sir, should I add first 21 calculators in generalMaths.html from old.html ??
there are more than 50 in that section under old.html

**Comment by sairish2001** [comment]
Actually 21 is just a demo text, add all the Calculators.
After that count how many Calculators are there, then replace 21 with that number. but leave this part, just focus on adding options.
@Divyanshj

**Comment by Divyanshj** [comment]
@sairish2001 Sir , I have linked a PR regarding this issue.
