### ISSUE TITLE
Luminosity calculator

### ISSUE THREAD

**Issue by Khushi-agarwal** [makesmatheasy/makesmatheasy#5373]
## **Is your feature request related to a problem? Please describe.**

I want to add luminosity calculator along with steps under the general maths section.
Please assign me under lgmsoc

**Comment by gnikita432** [comment]
Go ahead @Khushi-agarwal 
The deadline is 22/07/2021

**Comment by gnikita432** [comment]
@Khushi-agarwal Updates?

**Comment by Khushi-agarwal** [comment]
> @Khushi-agarwal Updates?

Made the PR. Apologies for being late.
