### ISSUE TITLE
Correction of Number of Calculators

### ISSUE THREAD

**Issue by ayushsagar10** [makesmatheasy/makesmatheasy#5377]
## **Describe the bug**

I want to add the correct number of calculators present in each section.
Please assign me this issue under LGMSOC'21

**Comment by ayushsagar10** [comment]
@sairish2001 @arpit456jain  Can you please assign me this issue under LGMSOC'21

**Comment by gnikita432** [comment]
Go ahead @ayushsagar10 
Deadline is 21/07/2021
