### ISSUE TITLE
Adding options under trigonometry section in menu

### ISSUE THREAD

**Issue by Divyanshj** [makesmatheasy/makesmatheasy#5379]
## **Describe the bug**

Trigonometry section is empty.

## **Screenshots**

![image](https://user-images.githubusercontent.com/72750492/125990199-c3b72ec3-ae83-4207-9e80-733bdea58d4e.png)

**Comment by gnikita432** [comment]
Go ahead @Divyanshj 
Deadline is 21/07/2021

**Comment by Divyanshj** [comment]
@sairish2001 Sir, I have submitted the PR with respect to this issue .
