### ISSUE TITLE
Align the Any base to any base convertor

### ISSUE THREAD

**Issue by Rizwan-S** [makesmatheasy/makesmatheasy#5381]
## **Describe the bug**
Currently, the 'Any base to any base convertor' is in the top left corner of the screen. Align it to the center of the screen.

**Comment by Sin-Sumit** [comment]
Hey, Can you please help me in finding the 'any base to any base calculator' that is located in which part?

**Comment by Rizwan-S** [comment]
It's in Binary section

**Comment by Sin-Sumit** [comment]
you need to put it in the center?

**Comment by Sin-Sumit** [comment]
Please assign it to me.

**Comment by Rizwan-S** [comment]
Go ahead. Make sure that you submit the PR by end of date for it to be considered for LGMSoC.

**Comment by Sin-Sumit** [comment]
What is the end date for LGMSoC?

**Comment by Sin-Sumit** [comment]
Hey, Rizwan is this okay, or totally need to be in the center?

**Comment by Sin-Sumit** [comment]
Please check the mail where I sent you the screenshot.

**Comment by Sin-Sumit** [comment]
Check this too.

**Comment by Rizwan-S** [comment]
Please make a PR with the relevant changes so that the team can review and suggest the necessary changes.
