### ISSUE TITLE
Half life calculator keep showing

### ISSUE THREAD

**Issue by JustinLemon** [makesmatheasy/makesmatheasy#5384]
## **Describe the bug**

I tried to click on "Leap year calculator" / "Profit loss calculator", but it keeps showing Half life calculator.

## **Possible solution**

Reorganize the buttons in General Maths

## **Screenshots**

![image](https://user-images.githubusercontent.com/86700378/126179667-1d3c7c28-d707-47f8-b30c-c5fdf2a5e3d6.png)

**Comment by gnikita432** [comment]
Go ahead @JustinLemon  
Deadline is 24/07/2021
