### ISSUE TITLE
Back button not working properly

### ISSUE THREAD

**Issue by ayushsagar10** [makesmatheasy/makesmatheasy#5385]
## **Describe the bug**

On scrolling down, the back button doesn't work properly. The button is not detected properly on hovering.

## **Screenshots**

![ss](https://user-images.githubusercontent.com/56185004/126205485-0a8d64cc-5859-415c-9681-4fab81efde04.png)

**Comment by gnikita432** [comment]
Go ahead @ayushsagar10 
Deadline is 24/07/2021
