### ISSUE TITLE
Adding section mensuration in the menu 

### ISSUE THREAD

**Issue by Divyanshj** [makesmatheasy/makesmatheasy#5386]
## **Is your feature request related to a problem? Please describe.**

Adding section mensuration in menu.html from old.html according to the previous ui.

## Screenshots

![image](https://user-images.githubusercontent.com/72750492/126211506-74e13303-ee6d-4aa1-9ed6-f8c70a9982b7.png)

**Comment by gnikita432** [comment]
@Divyanshj The UI of the site is changed now. Please have a look here https://makesmatheasy.github.io/makesmatheasy/

**Comment by Rizwan-S** [comment]
Go ahead @Divyanshj 
Deadline is 24/07/21
