### ISSUE TITLE
Leap Year Calculator No Results

### ISSUE THREAD

**Issue by JustinLemon** [makesmatheasy/makesmatheasy#5388]
## **Describe the bug**

Leap Year Calculator gives no results.

## **Possible solution**

Rewrite the logic for leap year calculator to show the results properly.

## **Screenshots**

![image](https://user-images.githubusercontent.com/86700378/126296532-4c54f8a7-4ed1-4df0-a436-44d276cd543f.png)

**Comment by JustinLemon** [comment]
Assign it to me.

**Comment by gnikita432** [comment]
Go ahead @JustinLemon 
Deadline is 25/07/2021
