### ISSUE TITLE
Adding back button to each calculator

### ISSUE THREAD

**Issue by stymm-1** [makesmatheasy/makesmatheasy#5390]
## **Is your feature request related to a problem? Please describe.**

-Back button is available when someone enter to group of calculator(e.g Linear Algebra) but no back button is available after entering a specific calculator(e.g AM/GM/HM)

## **Describe the solution you'd like**
I would like to add a back button to each and every calculator.

**Comment by gnikita432** [comment]
Go ahead @stymm-1 
The deadline is 27/07/2021
