### ISSUE TITLE
Factorial Calculator No Result

### ISSUE THREAD

**Issue by Sai0224** [makesmatheasy/makesmatheasy#5391]
## **Describe the bug**

Factorial Calculator gives no result.

## **Possible solution**

Complete the logic for Factorial Calculator to give output based on number input.

## **Screenshots**

![image](https://user-images.githubusercontent.com/63489792/126592418-a45dbc98-aa1b-4276-ad69-288c16151737.png)

**Comment by Sai0224** [comment]
Hi, may I have this issue assigned to me to solve it?

**Comment by Rizwan-S** [comment]
@Sai0224 Go ahead! 
Deadline: 27/07/21.

**Comment by Sai0224** [comment]
Thank you!
