### ISSUE TITLE
Sub calculators in trignometric section is not correctly linked.

### ISSUE THREAD

**Issue by stymm-1** [makesmatheasy/makesmatheasy#5397]
## **Describe the bug**

All the calculators in trigonometric sections are pointing to a single calculator (Ackermann function). 

## **Possible solution**

I would like to correct above mention issue by connecting each calculator to their respective calculator.

Please assign this issue to me.

**Comment by Rizwan-S** [comment]
Go ahead @stymm-1 
Deadline: 31/07/21
