### ISSUE TITLE
Kindly Read!

### ISSUE THREAD

**Issue by sairish2001** [makesmatheasy/makesmatheasy#5400]
@Khushi-agarwal
@Divyanshj
@jasminekaur-prog
@stymm-1
@jugeshraghav
@tjanhvi
@Sukhseerat-Kaur
@JustinLemon
@deepaahuja92
@PranavChauhan22
@akash435
@ayushsagar10
@siddhi-244
@Sai0224
@supzi-del
@surbhi594
@coding-geek21
@UG-SEP
@Umesh-01
@ROHAN842
@kshitija-2001
@RakeshCharpe
@codeaholic-shub
@puneetkaur2929

---

To get the Certificate of Contribution
Fill this form👇🏻

https://forms.gle/u9PagfFSzMXRNi5z9

---

**Comment by tjanhvi** [comment]
Can you please let me know when i got my certificate as  i already filled
the form also...

Thankyou

**Comment by sairish2001** [comment]
@tjanhvi as soon as the Program ends after than within 2days, i.e. 10 August,2021

**Comment by tjanhvi** [comment]
okok
