### ISSUE TITLE
Input FIelds In Quadratic calculator is different than other input fields.

### ISSUE THREAD

**Issue by Sin-Sumit** [makesmatheasy/makesmatheasy#5405]
## **Describe the bug**

In Quadratic calculator, to generate quadratic equation having given sum and products of roots have different input fields like other in that section.

## **Possible solution**

I can do it by adding some code in that file.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Screenshot from 2021-08-11 17-11-21](https://user-images.githubusercontent.com/48879218/129022898-38fc7208-355d-488d-ba91-84a2f23598cb.png)

**Comment by Sin-Sumit** [comment]
Will I start working on this?

**Comment by Sin-Sumit** [comment]
@sairish2001 Can I work on this? And I have one more request regarding the spaces between the input fields.

**Comment by sairish2001** [comment]
Go ahead @Sin-Sumit

**Comment by Sin-Sumit** [comment]
It is already solved.
Please check the last PR of mine.
