### ISSUE TITLE
Two declarations of function `Scientific`

### ISSUE THREAD

**Issue by donno2048** [makesmatheasy/makesmatheasy#5419]
https://github.com/makesmatheasy/makesmatheasy/blob/eb02f177b986296a75c8be60fb86852f93f50afe/nerdamer/nerdamer.core.js#L2719-L2843

https://github.com/makesmatheasy/makesmatheasy/blob/eb02f177b986296a75c8be60fb86852f93f50afe/nerdamer/nerdamer.core.js#L2851-L2980

why?

**Comment by sairish2001** [comment]
@donno2048 Go ahead!

**Comment by sairish2001** [comment]
@donno2048 Do you want to take this issue under Hacktoberfest?
