### ISSUE TITLE
Case-insensitive deletion

### ISSUE THREAD

**Issue by donno2048** [makesmatheasy/makesmatheasy#5420]
## **Describe the bug**

https://github.com/makesmatheasy/makesmatheasy/blob/main/calculators/areaOfCrescentAndLune.html

and

https://github.com/makesmatheasy/makesmatheasy/blob/main/calculators/areaOfCrescentandLune.html

Have the **exact** same name on case-insensitive operating systems which cause one of them to get auto-deleted

**Comment by donno2048** [comment]
Related:

[core.ignoreCase](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreignoreCase)

**Comment by sairish2001** [comment]
@donno2048 Go ahead

**Comment by donno2048** [comment]
`areaOfCrescentAndLune` appears just in [graphsShapes.html](https://github.com/makesmatheasy/makesmatheasy/blob/main/appdata/menudata/graphsShapes.html) here:
https://github.com/makesmatheasy/makesmatheasy/blob/c56ad9660cc06498e7b983e610eb9a576c39659e/appdata/menudata/graphsShapes.html#L231
though `areaOfCrescentandLune` looks more updated, I'll remove the old one and point `graphsShapes` towards the new one
