### ISSUE TITLE
Side-Nav Overlapping the upper nav-bar

### ISSUE THREAD

**Issue by sairish2001** [makesmatheasy/makesmatheasy#5423]
## **Describe the bug**

- Side nav bar is overlapping the upper nav bar

## **Screenshots**
![Capture](https://user-images.githubusercontent.com/60106112/135565646-7d71a301-295f-4b26-ae79-810c86e6b04c.PNG)

**Comment by Garima-7** [comment]
Can I work on this issue?

**Comment by Garima-7** [comment]
Assign me this issue.

**Comment by sairish2001** [comment]
@Garima-7 Go ahead

**Comment by Garima-7** [comment]
![Screenshot (451)](https://user-images.githubusercontent.com/83363645/135613936-68880c81-08d7-4e22-a15d-0d77b3c32a3f.png)
Is it fine now?
