### ISSUE TITLE
Scroll not working properly in Truth Table For Logical Operations page

### ISSUE THREAD

**Issue by zhcet19** [makesmatheasy/makesmatheasy#5429]
## **Describe the bug**

-![Screenshot 2021-10-03 134553](https://user-images.githubusercontent.com/55043876/135745680-08d0efd5-123f-49f5-9ea6-70648769708c.png) description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by zhcet19** [comment]
Yes,Please assign this issue under hacktoberfest tag

**Comment by sairish2001** [comment]
Go ahead @zhcet19

**Comment by zhcet19** [comment]
Is this participating in Hacktoberfest this year or not ??
![Uploading Screenshot 2021-10-04 104921.png…]()
