### ISSUE TITLE
Scroll feauter not working properly in Types of Relations page 

### ISSUE THREAD

**Issue by zhcet19** [makesmatheasy/makesmatheasy#5430]
![Screenshot 2021-10-03 135552](https://user-images.githubusercontent.com/55043876/135745931-dbe88509-953b-49f3-8dbc-fd95cf8692e6.png)

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by zhcet19** [comment]
Please assign me this issue under hacktoberfest tag

**Comment by sairish2001** [comment]
Go ahead @zhcet19
