### ISSUE TITLE
Divide by 0 should give invalid operation

### ISSUE THREAD

**Issue by zhcet19** [makesmatheasy/makesmatheasy#5433]
![Screenshot 2021-10-05 230441](https://user-images.githubusercontent.com/55043876/136074057-b5eb81f3-0a15-4ba8-80d2-a9ee4d51dc97.png)
## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by zhcet19** [comment]
@sairish2001 would you please assign me this under hacktoberfest

**Comment by sairish2001** [comment]
Go ahead @zhcet19
