### ISSUE TITLE
Show steps for calculation of Joint Probability

### ISSUE THREAD

**Issue by SarthakKeshari** [makesmatheasy/makesmatheasy#802]
## **Is your feature request related to a problem? Please describe.**

- Showing steps for calculation of Joint Probability

## **Describe the solution you'd like**

- Adding required functionality to code base

![Attention - Show Steps for joint probability calculation](https://user-images.githubusercontent.com/55992140/113471423-cca12a80-9479-11eb-8154-7d5377f588a7.PNG)

**Comment by SarthakKeshari** [comment]
Kindly assign this issue to me @sairish2001

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 April,2021 11:59 PM IST

**Comment by Ankita297** [comment]
Can i work on this @sairish2001  ?

**Comment by Ankita297** [comment]
@sairish2001 ?

**Comment by sairish2001** [comment]
Go ahead
