### ISSUE TITLE
Adding nth base root of a number option in a number

### ISSUE THREAD

**Issue by zhcet19** [makesmatheasy/makesmatheasy#837]
## **Is your feature request related to a problem? Please describe.**

- I want to add an option to calculate nth root of a number in calculator ,currently only square root is present

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by zhcet19** [comment]
@sairish2001  please assign me this issue

**Comment by sairish2001** [comment]
Go ahead
Deadline 10 April,2021 11:59 PM IST

**Comment by shonali2600** [comment]
@sairish2001 can I work on this?

**Comment by Samridhi-98** [comment]
@sairish2001  I would like to work on it please assign it to me.

**Comment by Ankita297** [comment]
@sairish2001 Can i work on this ?

**Comment by sairish2001** [comment]
@Ankita297 
Go ahead
Deadline 31 May,2021
