### ISSUE TITLE
Added little feautres to enhance user experience

### ISSUE THREAD

**Issue by Saumya-07** [makesmatheasy/makesmatheasy#906]
## Feature request

->Search items from the content in the website and if not found then it should direct to google

->Add enter button to search bar as it would provide a better user experience

->I found the positioning of the calculator a little off, it should either show up as a whole or direct the user to the new page  

I am a GSSOC participant and would be very happy to work on this project.

**Comment by sairish2001** [comment]
Go ahead
Deadline 15 April,2021 11:59 PM IST

**Comment by sairish2001** [comment]
Try not to add any new page

Try something in index.html, for the positioning of Calculator

**Comment by Saumya-07** [comment]
Thank you for assigning me this project 
I'll take care of the above mentioned

**Comment by anjali1102** [comment]
Hey @sairish2001  can you assign me this task, I will complete it in 3 days

**Comment by sairish2001** [comment]
No need of this issue
